// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Membership struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Role      pgtype.Text
	JoinedAt  pgtype.Timestamptz
}

type Message struct {
	ID        int64
	ProjectID pgtype.UUID
	SenderID  pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID           pgtype.UUID
	GithubRepoID int64
	FullName     string
	Name         string
	OwnerID      pgtype.UUID
	CreatedAt    pgtype.Timestamptz
}

type Rule struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	CriteriaType string
	Threshold    string
	CreatedAt    pgtype.Timestamptz
}

type User struct {
	ID               pgtype.UUID
	GithubID         int64
	Username         string
	AvatarUrl        pgtype.Text
	DisplayName      pgtype.Text
	AccessToken      string
	ProfileCompleted pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
