// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembership = `-- name: AddMembership :exec
INSERT INTO memberships (user_id, project_id, role)
VALUES ($1, $2, $3)
`

type AddMembershipParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Role      pgtype.Text
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.Exec(ctx, addMembership, arg.UserID, arg.ProjectID, arg.Role)
	return err
}

const addMessage = `-- name: AddMessage :exec
INSERT INTO messages (id, project_id , sender_id, content)
VALUES ($1, $2, $3, $4)
`

type AddMessageParams struct {
	ID        int64
	ProjectID pgtype.UUID
	SenderID  pgtype.UUID
	Content   string
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.Exec(ctx, addMessage,
		arg.ID,
		arg.ProjectID,
		arg.SenderID,
		arg.Content,
	)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (github_repo_id, name, owner_id)
VALUES ($1, $2, $3)
RETURNING id, github_repo_id, name, owner_id, created_at
`

type CreateProjectParams struct {
	GithubRepoID int64
	Name         string
	OwnerID      pgtype.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.GithubRepoID, arg.Name, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createRule = `-- name: CreateRule :one
INSERT INTO rules (project_id, criteria_type, threshold)
VALUES ($1, $2, $3)
RETURNING id, project_id, criteria_type, threshold, created_at
`

type CreateRuleParams struct {
	ProjectID    pgtype.UUID
	CriteriaType string
	Threshold    string
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule, arg.ProjectID, arg.CriteriaType, arg.Threshold)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CriteriaType,
		&i.Threshold,
		&i.CreatedAt,
	)
	return i, err
}

const getAllLoops = `-- name: GetAllLoops :many
SELECT 
    p.id,
    p.name,
    p.github_repo_id,
    p.created_at,
    u.username AS owner_username,
    u.avatar_url AS owner_avatar,
    (SELECT COUNT(*) FROM memberships m WHERE m.project_id = p.id) AS member_count
FROM projects p
JOIN users u ON p.owner_id = u.id
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllLoopsParams struct {
	Limit  int32
	Offset int32
}

type GetAllLoopsRow struct {
	ID            pgtype.UUID
	Name          string
	GithubRepoID  int64
	CreatedAt     pgtype.Timestamptz
	OwnerUsername string
	OwnerAvatar   pgtype.Text
	MemberCount   int64
}

func (q *Queries) GetAllLoops(ctx context.Context, arg GetAllLoopsParams) ([]GetAllLoopsRow, error) {
	rows, err := q.db.Query(ctx, getAllLoops, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllLoopsRow
	for rows.Next() {
		var i GetAllLoopsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GithubRepoID,
			&i.CreatedAt,
			&i.OwnerUsername,
			&i.OwnerAvatar,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoopMembers = `-- name: GetLoopMembers :many
SELECT 
    u.id,
    u.username,
    u.avatar_url,
    u.display_name,
    mem.role,
    mem.joined_at
FROM memberships mem
JOIN users u ON mem.user_id = u.id
WHERE mem.project_id = $1
ORDER BY mem.joined_at ASC
`

type GetLoopMembersRow struct {
	ID          pgtype.UUID
	Username    string
	AvatarUrl   pgtype.Text
	DisplayName pgtype.Text
	Role        pgtype.Text
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) GetLoopMembers(ctx context.Context, projectID pgtype.UUID) ([]GetLoopMembersRow, error) {
	rows, err := q.db.Query(ctx, getLoopMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLoopMembersRow
	for rows.Next() {
		var i GetLoopMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarUrl,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessages = `-- name: GetMessages :many
SELECT 
    m.id,
    m.content,
    m.created_at,
    m.sender_id,
    u.username AS sender_username,
    u.avatar_url AS sender_avatar
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.project_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMessagesParams struct {
	ProjectID pgtype.UUID
	Limit     int32
	Offset    int32
}

type GetMessagesRow struct {
	ID             int64
	Content        string
	CreatedAt      pgtype.Timestamptz
	SenderID       pgtype.UUID
	SenderUsername string
	SenderAvatar   pgtype.Text
}

func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.SenderID,
			&i.SenderUsername,
			&i.SenderAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, github_repo_id, name, owner_id, created_at FROM projects WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, github_repo_id, name, owner_id, created_at FROM projects WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByOwnerAndName = `-- name: GetProjectByOwnerAndName :one
SELECT id, github_repo_id, name, owner_id, created_at FROM projects
WHERE owner_id = $1 AND name = $2
LIMIT 1
`

type GetProjectByOwnerAndNameParams struct {
	OwnerID pgtype.UUID
	Name    string
}

func (q *Queries) GetProjectByOwnerAndName(ctx context.Context, arg GetProjectByOwnerAndNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByOwnerAndName, arg.OwnerID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectsByOwner = `-- name: GetProjectsByOwner :many
SELECT id, github_repo_id, name, owner_id, created_at
FROM projects
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.GithubRepoID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicProfile = `-- name: GetPublicProfile :one
SELECT
id,
username,
avatar_url,
display_name,
created_at
FROM users WHERE username = $1 LIMIT 1
`

type GetPublicProfileRow struct {
	ID          pgtype.UUID
	Username    string
	AvatarUrl   pgtype.Text
	DisplayName pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetPublicProfile(ctx context.Context, username string) (GetPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfile, username)
	var i GetPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getRulesByProject = `-- name: GetRulesByProject :many
SELECT id, project_id, criteria_type, threshold, created_at FROM rules
WHERE project_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetRulesByProject(ctx context.Context, projectID pgtype.UUID) ([]Rule, error) {
	rows, err := q.db.Query(ctx, getRulesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CriteriaType,
			&i.Threshold,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at FROM users WHERE github_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserMemberships = `-- name: GetUserMemberships :many
SELECT 
    p.id AS project_id,
    p.name AS project_name,
    mem.role,
    mem.joined_at
FROM memberships mem
JOIN projects p ON mem.project_id = p.id
WHERE mem.user_id = $1
ORDER BY mem.joined_at DESC
`

type GetUserMembershipsRow struct {
	ProjectID   pgtype.UUID
	ProjectName string
	Role        pgtype.Text
	JoinedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserMemberships(ctx context.Context, userID pgtype.UUID) ([]GetUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, getUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserMembershipsRow
	for rows.Next() {
		var i GetUserMembershipsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT
id,
github_id,
username,
avatar_url,
display_name,
profile_completed,
created_at
FROM users WHERE id = $1 LIMIT 1
`

type GetUserProfileRow struct {
	ID               pgtype.UUID
	GithubID         int64
	Username         string
	AvatarUrl        pgtype.Text
	DisplayName      pgtype.Text
	ProfileCompleted pgtype.Bool
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetUserProfile(ctx context.Context, id pgtype.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.ProfileCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const isMember = `-- name: IsMember :one
SELECT 1 FROM memberships
WHERE user_id = $1 AND project_id = $2 LIMIT 1
`

type IsMemberParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (int32, error) {
	row := q.db.QueryRow(ctx, isMember, arg.UserID, arg.ProjectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const searchRepos = `-- name: SearchRepos :many
SELECT id, name
FROM projects
WHERE name ILIKE $1 || '%'
ORDER BY similarity(name, $1) DESC
LIMIT $2
`

type SearchReposParams struct {
	Q pgtype.Text
	N int32
}

type SearchReposRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) SearchRepos(ctx context.Context, arg SearchReposParams) ([]SearchReposRow, error) {
	rows, err := q.db.Query(ctx, searchRepos, arg.Q, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReposRow
	for rows.Next() {
		var i SearchReposRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchReposFuzzy = `-- name: SearchReposFuzzy :many
SELECT id, name
FROM projects
WHERE name % $1
ORDER BY similarity(name, $1) DESC
LIMIT $2
`

type SearchReposFuzzyParams struct {
	Q string
	N int32
}

type SearchReposFuzzyRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) SearchReposFuzzy(ctx context.Context, arg SearchReposFuzzyParams) ([]SearchReposFuzzyRow, error) {
	rows, err := q.db.Query(ctx, searchReposFuzzy, arg.Q, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchReposFuzzyRow
	for rows.Next() {
		var i SearchReposFuzzyRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET
avatar_url = $2,
updated_at = NOW()
WHERE id = $1
RETURNING id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at
`

type UpdateUserAvatarParams struct {
	ID        pgtype.UUID
	AvatarUrl pgtype.Text
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
display_name = COALESCE($2, display_name),
profile_completed = TRUE,
updated_at = NOW()
WHERE id = $1
RETURNING id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID
	DisplayName pgtype.Text
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
	github_id, username, avatar_url, access_token
	) VALUES (
	$1, $2, $3, $4
)
ON CONFLICT (github_id) DO UPDATE SET
username = EXCLUDED.username,
avatar_url = COALESCE(users.avatar_url, EXCLUDED.avatar_url),
access_token = EXCLUDED.access_token,
updated_at = NOW()
RETURNING id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at
`

type UpsertUserParams struct {
	GithubID    int64
	Username    string
	AvatarUrl   pgtype.Text
	AccessToken string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GithubID,
		arg.Username,
		arg.AvatarUrl,
		arg.AccessToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
