// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMembership = `-- name: AddMembership :exec
INSERT INTO memberships (user_id, project_id, role)
VALUES ($1, $2, $3)
`

type AddMembershipParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Role      pgtype.Text
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.Exec(ctx, addMembership, arg.UserID, arg.ProjectID, arg.Role)
	return err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (github_repo_id, full_name, name, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id, github_repo_id, full_name, name, owner_id, created_at
`

type CreateProjectParams struct {
	GithubRepoID int64
	FullName     string
	Name         string
	OwnerID      pgtype.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.GithubRepoID,
		arg.FullName,
		arg.Name,
		arg.OwnerID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.FullName,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createRule = `-- name: CreateRule :one
INSERT INTO rules (project_id, criteria_type, threshold)
VALUES ($1, $2, $3)
RETURNING id, project_id, criteria_type, threshold, created_at
`

type CreateRuleParams struct {
	ProjectID    pgtype.UUID
	CriteriaType string
	Threshold    string
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule, arg.ProjectID, arg.CriteriaType, arg.Threshold)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CriteriaType,
		&i.Threshold,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByOwnerAndName = `-- name: GetProjectByOwnerAndName :one
SELECT id, github_repo_id, full_name, name, owner_id, created_at FROM projects
WHERE owner_id = $1 AND name = $2
LIMIT 1
`

type GetProjectByOwnerAndNameParams struct {
	OwnerID pgtype.UUID
	Name    string
}

func (q *Queries) GetProjectByOwnerAndName(ctx context.Context, arg GetProjectByOwnerAndNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByOwnerAndName, arg.OwnerID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.FullName,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectsByOwner = `-- name: GetProjectsByOwner :many
SELECT id, github_repo_id, full_name, name, owner_id, created_at
FROM projects
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, getProjectsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.GithubRepoID,
			&i.FullName,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicProfile = `-- name: GetPublicProfile :one
SELECT
    id,
    username,
    avatar_url,
    display_name,
    created_at
FROM users WHERE username = $1 LIMIT 1
`

type GetPublicProfileRow struct {
	ID          pgtype.UUID
	Username    string
	AvatarUrl   pgtype.Text
	DisplayName pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetPublicProfile(ctx context.Context, username string) (GetPublicProfileRow, error) {
	row := q.db.QueryRow(ctx, getPublicProfile, username)
	var i GetPublicProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at FROM users WHERE github_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT
    id,
    github_id,
    username,
    avatar_url,
    display_name,
    profile_completed,
    created_at
FROM users WHERE id = $1 LIMIT 1
`

type GetUserProfileRow struct {
	ID               pgtype.UUID
	GithubID         int64
	Username         string
	AvatarUrl        pgtype.Text
	DisplayName      pgtype.Text
	ProfileCompleted pgtype.Bool
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetUserProfile(ctx context.Context, id pgtype.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.ProfileCompleted,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET
    avatar_url = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at
`

type UpdateUserAvatarParams struct {
	ID        pgtype.UUID
	AvatarUrl pgtype.Text
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    display_name = COALESCE($2, display_name),
    profile_completed = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID
	DisplayName pgtype.Text
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    github_id, username, avatar_url, access_token
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (github_id) DO UPDATE SET
    username = EXCLUDED.username,
    avatar_url = COALESCE(users.avatar_url, EXCLUDED.avatar_url),
    access_token = EXCLUDED.access_token,
    updated_at = NOW()
RETURNING id, github_id, username, avatar_url, display_name, access_token, profile_completed, created_at, updated_at
`

type UpsertUserParams struct {
	GithubID    int64
	Username    string
	AvatarUrl   pgtype.Text
	AccessToken string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GithubID,
		arg.Username,
		arg.AvatarUrl,
		arg.AccessToken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Username,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.AccessToken,
		&i.ProfileCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
